In [2]:
import modern_robotics as mr
import numpy as np 

In [4]:
T = np.array([[0, 0, 1, -1],
             [-1, 0, 0, 0],
             [0, -1, 0, 0],
             [0, 0, 0, 1]])
mr.Adjoint(T)

array([[ 0.,  0.,  1.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.],
       [ 0., -1.,  0., -1.,  0.,  0.],
       [ 1.,  0.,  0.,  0., -1.,  0.]])

In [5]:
T = np.array([[1, 0, 0, 0],
             [0, 0, -1, 0],
             [0, 1, 0, -2],
             [0, 0, 0, 1]])
mr.Adjoint(T)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -2.,  1.,  0.,  0.],
       [-2.,  0.,  0.,  0.,  0., -1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.]])

In [6]:
T = np.array([[0, -1, 0, 3],
             [1, 0, 0, 0],
             [0, 0, 1, 1],
             [0, 0, 0, 1]])
mr.TransInv(T)

array([[ 0,  1,  0,  0],
       [-1,  0,  0,  3],
       [ 0,  0,  1, -1],
       [ 0,  0,  0,  1]])

In [7]:
V = np.array([1,0,0,0,2,3])
mr.VecTose3(V)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  2.],
       [ 0.,  1.,  0.,  3.],
       [ 0.,  0.,  0.,  0.]])

In [8]:
q = np.array([0,0,2])
s = np.array([1,0,0])
h = 1
mr.ScrewToAxis(q, s, h)

array([1, 0, 0, 1, 2, 0])

In [10]:
se3mat = np.array([[0, -1.5708, 0, 2.3562],
                  [1.5708, 0, 0, -2.3562],
                  [0, 0, 0, 1],
                  [0,0,0,0]])
mr.MatrixExp6(se3mat)

array([[-3.67320510e-06, -1.00000000e+00,  0.00000000e+00,
         3.00000551e+00],
       [ 1.00000000e+00, -3.67320510e-06,  0.00000000e+00,
         5.50981777e-06],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [11]:
T = np.array([[0, -1, 0, 3],
             [1, 0, 0, 0],
             [0, 0, 1, 1],
             [0, 0, 0, 1]])
mr.MatrixLog6(T)

array([[ 0.        , -1.57079633,  0.        ,  2.35619449],
       [ 1.57079633,  0.        ,  0.        , -2.35619449],
       [ 0.        ,  0.        ,  0.        ,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [12]:
T = np.array([[1, 0, 0, 0],
             [0, 0, 1, 2],
             [0, -1, 0, 0],
             [0, 0, 0, 1]])
mr.Adjoint(T)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  0.],
       [ 0., -2.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.],
       [-2.,  0.,  0.,  0., -1.,  0.]])